
import React, { useState } from 'react';
import { FileText, Download, Share2, CheckCircle2, History, Loader2, Phone } from 'lucide-react';
import { VitalRecord, Medication, Allergy } from '../types';
import { GlowingEffect } from './ui/glowing-effect';
import { jsPDF } from 'jspdf';

interface Props {
  vitals: VitalRecord[];
  meds: Medication[];
  allergies: Allergy[];
}

const ReportGenerator: React.FC<Props> = ({ vitals, meds, allergies }) => {
  const [isGenerating, setIsGenerating] = useState(false);
  const [doctorPhone, setDoctorPhone] = useState('');

  const generatePDF = () => {
    setIsGenerating(true);
    
    try {
      const doc = new jsPDF();
      const dateStr = new Date().toLocaleDateString();
      
      // Header
      doc.setFontSize(22);
      doc.setTextColor(59, 130, 246); // Blue-600
      doc.text('VitalPulse AI Health Report', 20, 20);
      
      doc.setFontSize(10);
      doc.setTextColor(100);
      doc.text(`Generated on: ${dateStr}`, 20, 28);
      doc.text('Confidential Medical Summary', 20, 33);
      
      // Patient Section
      doc.setFontSize(14);
      doc.setTextColor(30);
      doc.text('Patient Information', 20, 45);
      doc.setDrawColor(200);
      doc.line(20, 47, 190, 47);
      
      doc.setFontSize(11);
      doc.text('Name: John Doe', 20, 55);
      doc.text('Status: Active Monitoring', 20, 62);
      
      // Vitals Section
      doc.setFontSize(14);
      doc.text('Recent Vitals Summary', 20, 75);
      doc.line(20, 77, 190, 77);
      
      let y = 85;
      if (vitals.length > 0) {
        const latest = vitals[vitals.length - 1];
        doc.setFontSize(11);
        doc.text(`Blood Pressure: ${latest.bp} mmHg`, 25, y);
        doc.text(`Weight: ${latest.weight} kg`, 25, y + 7);
        doc.text(`Blood Sugar: ${latest.sugar} mg/dL`, 25, y + 14);
        doc.text(`Pulse Rate: ${latest.pulse} bpm`, 25, y + 21);
        y += 35;
      } else {
        doc.text('No vital records found.', 25, y);
        y += 15;
      }
      
      // Medications
      doc.setFontSize(14);
      doc.text('Active Medications', 20, y);
      doc.line(20, y + 2, 190, y + 2);
      y += 10;
      
      doc.setFontSize(11);
      if (meds.length > 0) {
        meds.forEach((med, i) => {
          doc.text(`• ${med.name} (${med.dosage}) - Scheduled: ${med.time}`, 25, y + (i * 7));
        });
        y += (meds.length * 7) + 10;
      } else {
        doc.text('No active medications reported.', 25, y);
        y += 15;
      }
      
      // Allergies
      doc.setFontSize(14);
      doc.setTextColor(225, 29, 72); // Rose-600
      doc.text('Known Allergies & Contraindications', 20, y);
      doc.line(20, y + 2, 190, y + 2);
      y += 10;
      
      doc.setFontSize(11);
      doc.setTextColor(30);
      if (allergies.length > 0) {
        allergies.forEach((allergy, i) => {
          doc.text(`• ${allergy.name} (${allergy.type}) - Severity: ${allergy.severity}`, 25, y + (i * 7));
        });
      } else {
        doc.text('No known allergies reported.', 25, y);
      }
      
      // Footer Disclaimer
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text('Disclaimer: This report is generated by AI for informational purposes only and is not a clinical diagnosis.', 20, 280);

      doc.save(`VitalPulse_Report_${dateStr.replace(/\//g, '-')}.pdf`);
    } catch (error) {
      console.error("PDF generation failed:", error);
      alert("Failed to generate PDF. Please check the console for details.");
    } finally {
      setIsGenerating(false);
    }
  };

  const shareWithDoctor = () => {
    if (!doctorPhone.trim()) {
      const phone = prompt("Please enter the doctor's WhatsApp number (with country code):");
      if (!phone) return;
      setDoctorPhone(phone);
    }

    const dateStr = new Date().toLocaleDateString();
    const latestVitals = vitals.length > 0 ? vitals[vitals.length - 1] : null;
    
    let summary = `*VitalPulse AI Health Report*\n`;
    summary += `*Date:* ${dateStr}\n`;
    summary += `*Patient:* John Doe\n\n`;
    
    summary += `*Latest Vitals:*\n`;
    if (latestVitals) {
      summary += `- BP: ${latestVitals.bp} mmHg\n`;
      summary += `- Weight: ${latestVitals.weight} kg\n`;
      summary += `- Sugar: ${latestVitals.sugar} mg/dL\n`;
    } else {
      summary += `- No recent records\n`;
    }
    
    summary += `\n*Medications:*\n`;
    meds.forEach(m => summary += `- ${m.name} (${m.dosage})\n`);
    
    summary += `\n*Allergies:*\n`;
    allergies.forEach(a => summary += `- ${a.name} (${a.severity} risk)\n`);
    
    const encoded = encodeURIComponent(summary);
    window.open(`https://wa.me/${doctorPhone.replace(/\+/g, '')}?text=${encoded}`, '_blank');
  };

  return (
    <div className="space-y-6">
      <div className="bg-gradient-to-br from-blue-600 to-indigo-700 p-8 rounded-3xl text-white shadow-xl relative overflow-hidden group">
        <GlowingEffect
          spread={100}
          glow={true}
          borderWidth={3}
          variant="white"
          className="opacity-50"
        />
        <div className="relative z-10">
          <h2 className="text-2xl font-bold mb-2">Smart Health Summary</h2>
          <p className="text-blue-100 text-sm mb-8 max-w-md">
            Generate a detailed medical report including your vitals, medications, and clinical notes to share with your physician.
          </p>
          <div className="flex flex-wrap gap-4">
            <button 
              onClick={generatePDF}
              disabled={isGenerating}
              className="px-6 py-3 bg-white text-blue-600 rounded-xl font-bold text-sm shadow-md hover:bg-blue-50 transition-all flex items-center gap-2"
            >
              {isGenerating ? <Loader2 className="w-5 h-5 animate-spin" /> : <Download className="w-5 h-5" />}
              {isGenerating ? 'Creating PDF...' : 'Download PDF Report'}
            </button>
            <button 
              onClick={shareWithDoctor}
              className="px-6 py-3 bg-emerald-500 text-white rounded-xl font-bold text-sm shadow-md hover:bg-emerald-600 transition-all flex items-center gap-2"
            >
              <Share2 className="w-5 h-5" /> Share via WhatsApp
            </button>
          </div>
          
          <div className="mt-6 flex items-center gap-2 bg-white/10 p-2 rounded-xl border border-white/20 w-fit">
            <Phone className="w-4 h-4 text-blue-100" />
            <input 
              type="text" 
              placeholder="Doctor's WhatsApp #" 
              value={doctorPhone}
              onChange={(e) => setDoctorPhone(e.target.value)}
              className="bg-transparent text-xs text-white placeholder:text-blue-200 focus:outline-none w-40"
            />
          </div>
        </div>
        <FileText className="absolute -right-4 -bottom-4 w-48 h-48 text-white/10 rotate-12" />
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="relative group bg-white p-6 rounded-2xl shadow-sm border border-slate-100 overflow-hidden">
          <GlowingEffect
            spread={50}
            glow={true}
            borderWidth={2}
          />
          <div className="relative z-10">
            <h3 className="font-bold text-lg text-slate-800 mb-6 flex items-center gap-2">
              <CheckCircle2 className="w-5 h-5 text-emerald-500" /> Live Report Preview
            </h3>
            <div className="space-y-4 text-sm text-slate-600">
              <div className="flex justify-between border-b border-slate-50 pb-2">
                <span>Patient Name:</span>
                <span className="font-bold text-slate-900">John Doe</span>
              </div>
              <div className="flex justify-between border-b border-slate-50 pb-2">
                <span>Vitals Logged:</span>
                <span className="font-bold text-slate-900">{vitals.length} records</span>
              </div>
              <div className="flex justify-between border-b border-slate-50 pb-2">
                <span>Current Medications:</span>
                <span className="font-bold text-slate-900">{meds.length} items</span>
              </div>
              <div className="flex justify-between border-b border-slate-50 pb-2 text-rose-600">
                <span>Critical Allergies:</span>
                <span className="font-bold">{allergies.filter(a => a.severity === 'High').length} high severity</span>
              </div>
            </div>
          </div>
        </div>

        <div className="relative group bg-white p-6 rounded-2xl shadow-sm border border-slate-100 overflow-hidden">
          <GlowingEffect
            spread={50}
            glow={true}
            borderWidth={2}
          />
          <div className="relative z-10">
            <h3 className="font-bold text-lg text-slate-800 mb-6 flex items-center gap-2">
              <History className="w-5 h-5 text-blue-500" /> Report History
            </h3>
            <div className="space-y-3">
              {[
                { date: 'Apr 15, 2024', name: 'Quarterly Checkup Report' },
                { date: 'Mar 10, 2024', name: 'Emergency Summary' },
                { date: 'Feb 28, 2024', name: 'Post-Surgery Vitals' },
              ].map((r, i) => (
                <div key={i} className="flex items-center justify-between p-3 bg-slate-50 rounded-xl hover:bg-slate-100 cursor-pointer group transition-colors">
                  <div className="flex items-center gap-3">
                    <FileText className="w-5 h-5 text-slate-400 group-hover:text-blue-500" />
                    <div>
                      <p className="text-sm font-bold text-slate-800">{r.name}</p>
                      <p className="text-[10px] text-slate-500 uppercase">{r.date}</p>
                    </div>
                  </div>
                  <Download className="w-4 h-4 text-slate-400" />
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ReportGenerator;